// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'gg',
    appId: '1:449676265981:web:8e3ee04618963fe5c43194',
    messagingSenderId: '449676265981',
    projectId: 'flutterapplication1-53250',
    authDomain: 'flutterapplication1-53250.firebaseapp.com',
    storageBucket: 'flutterapplication1-53250.appspot.com',
    measurementId: 'G-HRYBDEBLKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'gg',
    appId: '1:449676265981:android:561332da893fa6bcc43194',
    messagingSenderId: '449676265981',
    projectId: 'flutterapplication1-53250',
    storageBucket: 'flutterapplication1-53250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'gg',
    appId: '1:449676265981:ios:6c7d70133acab6b5c43194',
    messagingSenderId: '449676265981',
    projectId: 'flutterapplication1-53250',
    storageBucket: 'flutterapplication1-53250.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'gg',
    appId: '1:449676265981:ios:6c7d70133acab6b5c43194',
    messagingSenderId: '449676265981',
    projectId: 'flutterapplication1-53250',
    storageBucket: 'flutterapplication1-53250.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'gg',
    appId: '1:449676265981:web:012ca01114d8075ec43194',
    messagingSenderId: '449676265981',
    projectId: 'flutterapplication1-53250',
    authDomain: 'flutterapplication1-53250.firebaseapp.com',
    storageBucket: 'flutterapplication1-53250.appspot.com',
    measurementId: 'G-63G90YEENE',
  );
}
